# ============================================
# COMMON SPRING BOOT CONFIGURATION
# ============================================
spring:
  application:
    name: cms

  # Database Configuration
  datasource:
    url: jdbc:mysql://${HOST}:${PORT}/${DB_NAME}?useSSL=true&requireSSL=true&verifyServerCertificate=false
    username: ${USER_NAME}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  # Session Management
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

# Server Configuration
server:
  port: ${PORT:8080}
  servlet:
    session:
      timeout: 30m
      cookie:
        secure: true
        http-only: true
        same-site: lax

# Logging Configuration
logging:
  level:
    org:
      springframework:
        security: INFO
        web: INFO
      hibernate:
        SQL: ERROR
        type.descriptor.sql.BasicBinder: ERROR
    com.cms.system: DEBUG

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:aflflafljlqoeuoalajfldsjfjoiwerlljafljasf}
  expiration: 86400000 # 24 hours in milliseconds

# ============================================
# OPENAPI CONFIGURATION (COMMON)
# ============================================
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha
    filter: true

# ============================================
# DEVELOPMENT PROFILE
# ============================================
---
spring:
  config:
    activate:
      on-profile: dev

  # Development Database (if different from production)
  # datasource:
  #   url: jdbc:h2:mem:devdb
  #   username: sa
  #   password: password

# Development Server Configuration
server:
  servlet:
    session:
      cookie:
        secure: false # Allow HTTP in development

# Development OpenAPI/Swagger UI
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    try-it-out-enabled: true
    syntax-highlight:
      theme: monokai

# ============================================
# PRODUCTION PROFILE (DEFAULT)
# ============================================
---
spring:
  config:
    activate:
      on-profile: prod

# Production OpenAPI/Swagger UI (disabled by default)
springdoc:
  swagger-ui:
    enabled: false

# Production Security Headers
server:
  servlet:
    session:
      cookie:
        secure: true
        http-only: true
        same-site: lax
# Optional: Uncomment and configure for production
# spring.redis.host=your-redis-host
# spring.redis.port=6379
# spring.cache.type=redis

# Optional: API Documentation Groups
# springdoc:
#   group-configs:
#     - group: users
#       paths-to-match: /api/users/**
#     - group: products
#       paths-to-match: /api/products/**
